# Site settings
title: "PHYS60441: W-Projection Lecture"
email: anna.scaife@manchester.ac.uk
description: "Special lecture for PHYS60441 Radio Interferometry course"
baseurl: "/phys60441"
url: "http://as595.github.io"
twitter_username: radastrat
github_username:  as595

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
